### ISSUE TITLE
Removed login button

### ISSUE THREAD

**Issue by vMotionFailed** [leram84/layer.Cake#9]
It seems a recent update to the css deleted the login button for organizr.  I just removed the theme by deleting the custom.css file and it brought back the login button on the top right.  I tried different browsers and clearing cache etc.. seems to just be something in the css.  Your designed a really awesome theme, as soon as it doesn't delete my login button I'll add it again.

**Comment by leram84** [comment]
yeah, so I actually just pushed v1.0 (was previously in beta), and there were a couple of breaking changes with this update, which i knew i was going to have to do 1 time, which is why i started with a beta. From here on out, all upgrades will be optional and won't break anything, but this was necessary. If you upgrade the theme (same way you installed it initially), you should be good to go. Sorry for the inconvenience!

**Comment by leram84** [comment]
wait a minute... sorry, i just saw "removed button" and just assumed u were talking about the user drop down button in the top right of org (which is something i did have to rework in 1.0). Are you actually talking about the login button? because I haven't touched that, and its still working fine on my end

**Comment by leram84** [comment]
Nevermind. I saw what you were talking about (i believe). If you were referring to the button in the top bar, that was actually a pretty interesting bug lol. But anyway, all good now. lmk if I missed anything.

**Comment by vMotionFailed** [comment]
Thanks for the quick reply, I saw it but didn't have time to reply.  Yeah it's back now, it was the login button in the top bar.  I took a quick look at the css and everything looked normal, I'm sure it was pretty interesting.  If I had to guess maybe something with z-index layering or it wasn't correctly determining when someone was logged in.  Either way thanks for fixing, it's an awesome theme.
